# Generated by Django 4.1.5 on 2023-01-03 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.PositiveBigIntegerField(unique=True)),
                ('password', models.CharField(max_length=50)),
                ('time', models.IntegerField(default=1672742635)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datenotes', models.CharField(max_length=10, unique=True)),
                ('text', models.TextField(max_length=1000000)),
                ('edit', models.BooleanField(default=False)),
                ('datalogin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy_app.user')),
            ],
        ),
    ]
