# Generated by Django 4.1.4 on 2022-12-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameBook', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('yearCreate', models.DateField()),
                ('style', models.CharField(choices=[('Horror', 'Horror'), ('Drama', 'Drama')], default='Drama', max_length=100)),
                ('public', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('img', models.ImageField(upload_to='images/')),
                ('img_base64', models.CharField(blank=True, max_length=200000)),
            ],
        ),
    ]
