# Generated by Django 4.1.3 on 2022-12-09 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_aapp', '0002_departments_diseases_doctors_examinations_wards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseases',
            name='severity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
