# Generated by Django 4.1.3 on 2022-12-13 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('four_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='places',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
