# Generated by Django 4.1.4 on 2022-12-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchNumber', models.IntegerField()),
                ('roundNumber', models.IntegerField()),
                ('dateUtc', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('homeTeam', models.CharField(max_length=100)),
                ('awayTeam', models.CharField(max_length=100)),
                ('group', models.CharField(blank=True, max_length=100)),
                ('homeTeamScore', models.IntegerField(blank=True)),
                ('awayTeamScore', models.IntegerField(blank=True)),
            ],
        ),
    ]
