# Generated by Django 4.1.4 on 2022-12-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_alter_productmodel_awayteamscore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='group',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
