# Generated by Django 4.1.4 on 2022-12-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_alter_productmodel_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='awayTeamScore',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='group',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='homeTeamScore',
            field=models.IntegerField(null=True),
        ),
    ]
