# Generated by Django 4.1.4 on 2023-01-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tel_app', '0002_alter_pay_cvv_alter_pay_date_alter_pay_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='date',
            field=models.IntegerField(null=True),
        ),
    ]
